version: '3'
services:
  frontend:
    build : './frontend'
    image : frontend:latest
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/frontend
    ports:
      - 80:80
  backend:
    build : './backend'
    image : backend:latest
    container_name: backend
    ports:
      - 3000:80
  mongodb:
    image: mongo:4.4.29-focal
    ports: 
      - 27017:27017
    volumes:
      - ./data:/data/db