version: '3'
services:
  frontend:
    build : './frontend'
    image : frontend:latest
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/frontend
    ports:
      - 3000:3000
    networks:
      - peppino
    depends_on:
      - app
  app:
    build : './app'
    image : app:latest
    container_name: app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 4000:4000
    networks:
      - peppino
    depends_on:
      - backend
  backend:
    build : './backend'
    image : backend:latest
    container_name: backend
    expose:
      - 5000
    ports:
      - 5000:5000
    networks:
      - peppino
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.29-focal
    container_name: mongodb
    ports: 
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    networks:
      - peppino
networks:
  peppino:
    driver: bridge